In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
import datetime
import sys

In [2]:
from pandas.tseries.offsets import Day,MonthEnd

In [2]:
In [15]: values = pd.Series([0, 1, 0, 0] * 2)
In [16]: dim = pd.Series(['apple', 'orange'])

In [3]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [4]:
In [20]: fruits = ['apple', 'orange', 'apple', 'apple'] * 2
In [21]: N = len(fruits)
In [22]: df = pd.DataFrame({'fruit': fruits,
....: 'basket_id': np.arange(N),
....: 'count': np.random.randint(3, 15, size=N),
....: 'weight': np.random.uniform(0, 4, size=N)},
....: columns=['basket_id', 'fruit', 'count', 'weight'])

In [5]:
df

basket_id   fruit  count    weight
0          0   apple      6  1.816410
1          1  orange     12  2.088720
2          2   apple      9  1.143751
3          3   apple     13  1.935277
4          4   apple      3  2.214654
5          5  orange     12  0.113986
6          6   apple     11  1.489586
7          7   apple      5  1.982147

In [6]:
fruit_cat = df['fruit'].astype('category')

In [9]:
c = fruit_cat.values

In [10]:
type(c)

pandas.core.categorical.Categorical

In [11]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [13]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [14]:
df['fruit'] = df['fruit'].astype('category')

In [15]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [16]:
In [34]: categories = ['foo', 'bar', 'baz']
In [35]: codes = [0, 1, 2, 0, 0, 1]
In [36]: my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [17]:
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [18]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
....: ordered=True)

In [19]:
ordered_cat

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [20]:
ordered_cat.sort_values()

[foo, foo, foo, bar, bar, baz]
Categories (3, object): [foo < bar < baz]

In [21]:
my_cats_2.as_ordered()

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [22]:
In [41]: np.random.seed(12345)
In [42]: draws = np.random.randn(1000)

In [23]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [24]:
bins = pd.qcut(draws,4)

In [25]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [26]:
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [29]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [30]:
In [49]: bins = pd.Series(bins, name='quartile')
In [50]: results = (pd.Series(draws)
....: .groupby(bins)
....: .agg(['count', 'min', 'max'])
....: .reset_index())
In [51]: results


quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

时间序列

In [3]:
from datetime import datetime

In [4]:
now = datetime.now()

In [5]:
now

datetime.datetime(2018, 10, 31, 13, 57, 24, 679981)

In [6]:
now + 3 * Day()

Timestamp('2018-11-03 13:57:24.679981')

In [7]:
now + MonthEnd()

Timestamp('2018-11-30 13:57:24.679981')

In [8]:
offset = MonthEnd()

In [9]:
offset.rollback(now)

Timestamp('2018-10-31 13:57:24.679981')

In [14]:
ts = DataFrame(np.random.randn(20),index = pd.date_range('20181001',periods = 20,freq = "4D"))

In [17]:
ts.columns = ['A']

In [18]:
ts.groupby(offset.rollforward).mean()

A
2018-10-31 -0.053276
2018-11-30 -0.300207
2018-12-31 -0.293273

In [19]:
ts

A
2018-10-01 -2.106038
2018-10-05 -0.441035
2018-10-09 -1.264487
2018-10-13  2.629426
2018-10-17  1.294415
2018-10-21 -0.134895
2018-10-25  0.623166
2018-10-29 -1.026758
2018-11-02 -0.451203
2018-11-06  0.082234
2018-11-10  0.513808
2018-11-14 -0.716493
2018-11-18  0.077951
2018-11-22 -0.662010
2018-11-26 -0.744075
2018-11-30 -0.501866
2018-12-04 -1.302695
2018-12-08 -1.675480
2018-12-12  1.159694
2018-12-16  0.645389

In [20]:
ts.resample('M').mean()

A
2018-10-31 -0.053276
2018-11-30 -0.300207
2018-12-31 -0.293273

In [21]:
import pytz

In [22]:
pytz.all_timezones

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Asmera', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Timbuktu', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'Ameri

In [4]:
df = DataFrame(np.arange(10),index = pd.date_range('20181010',periods = 10),columns = ['A'])

In [5]:
df.rolling(3).sum()

A
2018-10-10   NaN
2018-10-11   NaN
2018-10-12   3.0
2018-10-13   6.0
2018-10-14   9.0
2018-10-15  12.0
2018-10-16  15.0
2018-10-17  18.0
2018-10-18  21.0
2018-10-19  24.0

In [2]:
df = pd.DataFrame(np.random.randint(0,5,(6, 2)), columns=['col1','col2'])

In [3]:
df

col1  col2
0     1     2
1     0     0
2     3     4
3     1     0
4     1     1
5     4     1

In [2]:
s = Series(range(8),index = [x for x in "ABCDEFGH"])

In [5]:
for x,s in s.items():
    print(x,s)

A 0
B 1
C 2
D 3
E 4
F 5
G 6
H 7
