# NumPy的使用

## NumPy的功能

* ndarray数组
* 向量计算的函数
* 文件读写工具
* 和其他语言接口
* 线性代数、傅里叶变换等

## ndarray数组

In [2]:
import numpy as np

In [3]:
# 生成一些随机数
data = np.random.randn(2,3)
data

array([[-2.47831788, -0.26839804,  0.21426386],
       [-0.49619718, -0.49582281, -0.07913672]])

In [4]:
data.dtype

dtype('float64')

ndarray数组是一个同构数据的容器，每一个数组都有一个**shape**数组的维度及各维度的尺寸及一个**dtype**数据类型

> 笔记：当你在本书中看到“数组”、“NumPy数组”、"ndarray"时，基本上都指的是同一样东西，即ndarray对象。

#### 创建ndarray数组

In [5]:
data_nd = [2,3,4,5,8]
data_np = np.array(data_nd)
data_np

array([2, 3, 4, 5, 8])

In [6]:
data_np.shape

(5,)

In [7]:
data_nd2 = [[2,3,4],[7,8,9]]
data_np2 = np.array(data_nd2)
data_np2

array([[2, 3, 4],
       [7, 8, 9]])

In [9]:
data_np2.shape

(2, 3)

In [10]:
data_np2.ndim

2

In [11]:
np.zeros(12)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.ones(3)

array([ 1.,  1.,  1.])

In [14]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

> **注意：认为np.empty会返回全0数组的想法是不安全的。很多情况下（如前所示），它返回的都是一些未初始化的垃圾值。**

##### arange是python里函数range的np版

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

####  ndarray构造函数

![](.\imgs\7178691-78ab11f67e7077a6.png)

#### 数据类型dtype和数据类型转换astype

In [17]:
data_np.dtype

dtype('int32')

In [16]:
data_np.astype('float32')

array([ 2.,  3.,  4.,  5.,  8.], dtype=float32)

In [19]:
In [44]: numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [45]: numeric_strings.astype(float)



array([  1.25,  -9.6 ,  42.  ])

> 笔记：**调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。**

## 数组运算

数组很重要，因为它使你不用编写循环即可对数据执行批量运算。NumPy用户称其为矢量化（vectorization）。大小相等的数组之间的任何算术运算都会将运算应用到元素级：

In [20]:
arr = np.array([[2,3,4],[4,5,6]])
arr * arr

array([[ 4,  9, 16],
       [16, 25, 36]])

In [22]:
arr.dot(np.transpose(arr))

array([[29, 47],
       [47, 77]])

In [23]:
1/arr

array([[ 0.5       ,  0.33333333,  0.25      ],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [24]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr > arr2

array([[ True, False,  True],
       [False,  True, False]], dtype=bool)